/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2024-04-05 06:00:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class submit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<h1>heyy submit</h1>\r\n");
      out.write(" <script\r\n");
      out.write(" \tsrc=\"https://code.jquery.com/jquery-3.6.0.min.js\">\r\n");
      out.write(" </script>\r\n");
      out.write("  ");
 String name = request.getParameter("name"); 
      out.write("\r\n");
      out.write("    ");
 String email = request.getParameter("email");
    
      out.write("\r\n");
      out.write("   ");
 String[] nameArray = {"laksh","sujay","saurabh"};
   		StringBuilder jsonArray = new StringBuilder("[");
   		for(int i=0;i<nameArray.length;i++){
   			jsonArray.append("'"+nameArray[i]+"'");
   			if(i<nameArray.length-1){
   				jsonArray.append(", ");
   			}
   		}
   		jsonArray.append("]");
   		
   
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <p>Name: ");
      out.print( name );
      out.write("</p>\r\n");
      out.write("    <p>Email: ");
      out.print( email );
      out.write("</p>\r\n");
      out.write("     <button onclick=\"myFunction()\">Click Me</button>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function myFunction(){\r\n");
      out.write("    \tconsole.log(\"calling myFunction\");\r\n");
      out.write("    \tconsole.log(\"my name\"+ \"");
      out.print(name );
      out.write("\");\r\n");
      out.write("\t\tname =\"");
      out.print(name );
      out.write("\";\r\n");
      out.write("\t\tparamNamesC=\"");
      out.print(jsonArray.toString() );
      out.write("\";\r\n");
      out.write("\t\tconsole.log(\"yyyy\"+paramNamesC)\r\n");
      out.write("\t\tjsonDataToSend= JSON.stringify(paramNamesC);\r\n");
      out.write("\t\tconsole.log(\"hey n\"+jsonDataToSend);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  $.ajax({\r\n");
      out.write("              url: \"process.jsp\", // URL of the JSP file you want to send the AJAX request to\r\n");
      out.write("              method: \"POST\",\r\n");
      out.write("              data: {\r\n");
      out.write("                  param1:name,\r\n");
      out.write("                  param2:jsonDataToSend\r\n");
      out.write("              },\r\n");
      out.write("              success: function(response) {\r\n");
      out.write("                  // Handle the response here\r\n");
      out.write("               \tconsole.log(\"response is here  \"+response);\r\n");
      out.write("              },\r\n");
      out.write("              error: function( error) {\r\n");
      out.write("                  // Handle errors here\r\n");
      out.write("                  console.error(error);\r\n");
      out.write("              }\r\n");
      out.write("          });\r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("    </script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
